amazon:
  access:
    key: AKIATW5KNR2JB33O6RXG
    secret-key: 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
  region: us-east-1
  sqs:
    queue:
      complains: complains
      attendance: attedence


server:
  port: 9002
